### ISSUE TITLE
@某人前输入@符号问题

### ISSUE THREAD

**Issue by LJYq** [CarGuo/RickText#12]
在有@某人前，不管是@某人前中间有文本还有没有文本，输入@符号之后跳转选择@用户回来文本并没有填充上还有@符号并没有删除。但是在@某人后输入@符号之后跳转回来是正常的。请问作者这是怎么回事呢？谢谢！

**Comment by CarGuo** [comment]
新版本2.1.0试试

**Comment by LJYq** [comment]
可以了，感谢作者！
