### ISSUE TITLE
希望科特林和java版本能分开。

### ISSUE THREAD

**Issue by q805699513** [CarGuo/RickText#15]
导入demo后databinding编译报错。

**Comment by CarGuo** [comment]
本来就是分开的，你可以屏蔽setting下的kotlin两个模块。

**Comment by q805699513** [comment]
导入demo后编译databinding报错。

**Comment by CarGuo** [comment]
本来就是分开的，你可以屏蔽setting下的kotlin两个模块。

至于编译错误的log是什么？
