### ISSUE TITLE
删除的bug 

### ISSUE THREAD

**Issue by KeqingLI** [CarGuo/RickText#18]
如
@CarGuo\b*#AAA# 
如果光标在*号处点击删除 会把#AAA一起删除

**Comment by CarGuo** [comment]
这个问题跟下

**Comment by KeqingLI** [comment]
RichEditText ->resolveAtPersonEditText ->onTextChanged 方法   getText().replace(position, position + length, ""); 会重新触发文本改变监听 导致后面的被删除
我添加了一行    delIndex = -1; 暂不知会不会引发其他问题
` public void onTextChanged(CharSequence s, int start, int before, int count) {
                String setMsg = s.toString();
                if (delIndex != -1) {
                    if (length > 1) {
                        resolveDeleteName();
                        resolveDeleteTopic();
                    //    resolveDeleteGroup();
                        int position = delIndex;
                        delIndex = -1;
                        try {
                            getText().replace(position, position + length, "");
                            setSelection(position);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                    delIndex = -1;
                } else {
                    if (setMsg.length() >= beforeCount && getSelectionEnd() > 0 && setMsg.charAt(getSelectionEnd() - 1) == '@') {
                        if (editTextAtUtilJumpListener != null) {
                            editTextAtUtilJumpListener.notifyAt();
                        }
                    } else if (setMsg.length() >= beforeCount && getSelectionEnd() > 0 && setMsg.charAt(getSelectionEnd() - 1) == '#') {
                        if (editTextAtUtilJumpListener != null) {
                            editTextAtUtilJumpListener.notifyTopic();
                        }
                    } else if (setMsg.length() >= beforeCount && getSelectionEnd() > 0 && setMsg.charAt(getSelectionEnd() - 1) == '&') {
                        if (editTextAtUtilJumpListener != null) {
                            editTextAtUtilJumpListener.notifyTopic();
                        }
                    }
                }
         
            }`

**Comment by CarGuo** [comment]
如果测试没问题可以劳烦提交一个pr可以不？

**Comment by CarGuo** [comment]
已发布修复。
