### ISSUE TITLE
RichEditText resolveInsertText

### ISSUE THREAD

**Issue by KeqingLI** [CarGuo/RickText#19]
RichEditText的resolveInsertText方法 添加的listUser和listTopic 并未加入nameList和topicList,导致getReal系列的获取值发生错误 

大佬，你这个库靠谱么 改得我好痛苦

**Comment by CarGuo** [comment]
你在调用前需要设置setModelList，demo中忘记了，这个设置是想着直接替换原来的

**Comment by KeqingLI** [comment]
我现在是在resolveInsertText方法中进行的处理 
另外问下RichTextView展示的时候 listUser与text中@用户的顺序不同 目前你的处理是不能正常显示的，我看你的匹配是必须顺序的才行 是有特殊的考虑么

**Comment by CarGuo** [comment]
这个是参考项目的做法

**Comment by KeqingLI** [comment]
我改为用正则解决匹配所有的了
另外想问下
`
         for (int i = 0; i < length; i++) {
                if (matcher.find()) {
               }
        }
`
项目中很多这种写法 为什么不采用    while(matcher.find())  我进行了修改 不知是否有问题

**Comment by CarGuo** [comment]
理论是没有什么问题
