### ISSUE TITLE
与SpannableString 结合使用，表情解析不出来

### ISSUE THREAD

**Issue by Reteyery** [CarGuo/RickText#2]
emojiText = TextCommonUtils.getEmojiText(mContext, entity.getComment_content());
                SpannableString spannableString = new SpannableString(mContext.getString(R.string.reply) + entity.getCommented_user_nick() + ":" + emojiText);
                spannableString.setSpan(new ForegroundColorSpan(mContext.getColor(R.color.font_blue_v2)), 2, entity.getCommented_user_nick().length() + 2, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
                holder.tvSayWhat.setText(spannableString);
代码实现的是回复评论的功能，eg:  回复XXX:内容+表情， 对XXX加了字体颜色，但是表情。。解析不出来了。这块怎么处理，求给个思路

**Comment by CarGuo** [comment]
demo中不是已经实现了表情加字体颜色么

**Comment by Reteyery** [comment]
我的错，刚才又看了下代码，抱歉
