### ISSUE TITLE
大佬 帮忙看个问题 实在是没找到修改的地方

### ISSUE THREAD

**Issue by KeqingLI** [CarGuo/RickText#20]
Demo里输入一个话题 点击删除键 光标选中的是整个话题 这时候用键盘随便输入字符进去覆盖  输入进去的字符是话题的颜色

**Comment by CarGuo** [comment]
话题和@人在设置进去的时候使用不同的方式，你可以看看两个的区别，一个是span一个是html

**Comment by KeqingLI** [comment]
我估计也是span上出了问题  新输入的沿用了之前是span 对这一块不是太熟 确实没发现是哪出了问题

**Comment by KeqingLI** [comment]
你能估计下是MentionEditText的问题还是RichEditText里面造成的么 我预估是MentionEditText的问题 但在这里面确实没找到原因  RichEditText里也就字符改变监听那有调用 也没看出什么原因

**Comment by CarGuo** [comment]
RichEditText里的，其实就是span占据了位置导致，你可以看看在插入的时候，at人和话题的区别，和motion没关系

**Comment by KeqingLI** [comment]
好的 晚上回去看看
