### ISSUE TITLE
在edittext中删除@的用户的昵称后，list中的昵称和id均未删除

### ISSUE THREAD

**Issue by pengchao1989** [CarGuo/RickText#3]
操作步骤：
1.在通过点击at按钮或者输入@字符
2.选择用户名
3.通过EditTextAtUtils的相关方法插入@的用户
4.通过软键盘的删除键删除对应的@用户
5.最后发现list中的昵称和id未变化

**Comment by CarGuo** [comment]
哪个版本的？demo 中貌似不会啊

**Comment by CarGuo** [comment]
2.0.6
