### ISSUE TITLE
@的用户名以及content中在昵称后面发现有/b

### ISSUE THREAD

**Issue by pengchao1989** [CarGuo/RickText#4]
因为有/b在后续展示部分会出现匹配不出，导致展示无法高亮，在数据库中删除掉对应的/b就会正常

**Comment by CarGuo** [comment]
其实是这样的，\b上传的时候并不需要上传，我们的做法是，上传的时候把\b替换成其他符号，在数据会到的时候吧其他符号替换成\b这样
